### ISSUE TITLE
engine.load() не арбайтен

### ISSUE THREAD

**Issue by simsanutiy** [IlyaGusev/rupo#11]
При попытке запуска по инструкции для анализа из readme:
```
>>> engine.load()
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    engine.load()
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 38, in load
    stress_trie_path, zalyzniak_dict)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 75, in get_stress_predictor
    zalyzniak_dict, cmu_dict)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\stress\predictor.py", line 150, in __init__
    self.rnn = RNNGraphemeStressPredictor(language, stress_model_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\stress\predictor.py", line 36, in __init__
    raise RuntimeError("No stress model available (or wrong path)")
RuntimeError: No stress model available (or wrong path)
```
Так же не получается запустить генерацию, тоже всё по инструкции:
```
>>> engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 201, in generate_poem
    stress_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 64, in get_lstm_generator
    lstm = LSTMModelContainer(model_path, word_form_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 232, in __init__
    self.lstm.prepare(list(), word_form_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 65, in prepare
    self.grammeme_vectorizer = GrammemeVectorizer(gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 33, in __init__
    self.load()
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 41, in load
    vectorizer = jsonpickle.decode(f.read())
  File "D:\Python_3.5.2_x64\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 10546: character maps to <undefined>
```

**Comment by IlyaGusev** [comment]
Поправил, поменял интерфейс load, чтобы он явно принимал модель и словарь. В генерации была проблема с кодировкой по умолчанию, для Windows она cp1251, а файл в utf-8, поправил.

**Comment by simsanutiy** [comment]
Возможно это я что-то не так ввожу?
```
>>> engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 200, in generate_poem
    stress_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 63, in get_lstm_generator
    lstm = LSTMModelContainer(model_path, word_form_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 232, in __init__
    self.lstm.prepare(list(), word_form_vocab_dump_path, gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 65, in prepare
    self.grammeme_vectorizer = GrammemeVectorizer(gram_dump_path)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 33, in __init__
    self.load()
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 41, in load
    vectorizer = jsonpickle.decode(f.read())
  File "D:\Python_3.5.2_x64\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by IlyaGusev** [comment]
Ох, прошу прощения, в Readme не обновил ссылку на модель, сейчас там правильная.

**Comment by IlyaGusev** [comment]
В итоге получилось?

**Comment by simsanutiy** [comment]
Чувствую, это может продолжаться вечно
```
>>> engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)

Init vocabulary:   0%|          | 0/1 [00:00<?, ?it/s]
Init vocabulary: 100%|##########| 1/1 [00:00<00:00, 999.36it/s]
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.pickle', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 201, in generate_poem
    return generator.generate_poem(metre_schema, rhyme_pattern, n_syllables, beam_width=beam_width)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 139, in generate_poem
    paths += self.generate_line_beam(path, beam_width)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 156, in generate_line_beam
    paths = self.generate_paths(path, beam_width, use_rhyme=True)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 180, in generate_paths
    model = path.get_current_model(self.model_container, self.vocabulary, use_rhyme)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 77, in get_current_model
    model = model_container.get_model(self.indices)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 237, in get_model
    return self.lstm.predict(word_indices[-self.cut_context:])
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 201, in predict
    grammeme_vectorizer=self.grammeme_vectorizer)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\batch_generator.py", line 94, in get_sample
    grammemes_vector = [grammeme_vectorizer.get_vector_by_index(x.gram_vector_index) for x in sentence]
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\batch_generator.py", line 94, in <listcomp>
    grammemes_vector = [grammeme_vectorizer.get_vector_by_index(x.gram_vector_index) for x in sentence]
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 103, in get_vector_by_index
    return self.vectors[index] if 0 <= index < len(self.vectors) else [0] * len(self.vectors[0])
IndexError: list index out of range
```

**Comment by IlyaGusev** [comment]
Так там другой векторизатор уже, grammeme_vectorizer.json, у тебя путь неправильный

**Comment by simsanutiy** [comment]
Вот для таких (очень глупых) людей как я и пишутся подробные инструкции на всём, что движется. Однако:
```
>>> engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.json', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    engine.generate_poem('D:\poem\models\lstm.h5', 'D:\poem\models\word_form_vocabulary.pickle', 'D:\poem\models\grammeme_vectorizer.json', 'D:\poem\models\stress_vocabulary.pickle', beam_width=3, n_syllables=8)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\api.py", line 201, in generate_poem
    return generator.generate_poem(metre_schema, rhyme_pattern, n_syllables, beam_width=beam_width)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 139, in generate_poem
    paths += self.generate_line_beam(path, beam_width)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 156, in generate_line_beam
    paths = self.generate_paths(path, beam_width, use_rhyme=True)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 180, in generate_paths
    model = path.get_current_model(self.model_container, self.vocabulary, use_rhyme)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\generator.py", line 77, in get_current_model
    model = model_container.get_model(self.indices)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 237, in get_model
    return self.lstm.predict(word_indices[-self.cut_context:])
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\lstm.py", line 201, in predict
    grammeme_vectorizer=self.grammeme_vectorizer)
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\batch_generator.py", line 94, in get_sample
    grammemes_vector = [grammeme_vectorizer.get_vector_by_index(x.gram_vector_index) for x in sentence]
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\language_model\batch_generator.py", line 94, in <listcomp>
    grammemes_vector = [grammeme_vectorizer.get_vector_by_index(x.gram_vector_index) for x in sentence]
  File "D:\Python_3.5.2_x64\lib\site-packages\rupo\generate\prepare\grammeme_vectorizer.py", line 103, in get_vector_by_index
    return self.vectors[index] if 0 <= index < len(self.vectors) else [0] * len(self.vectors[0])
IndexError: list index out of range
```

**Comment by IlyaGusev** [comment]
Проверил на свежей машине, всё ок. 
Во-первых, обязательно нужно сделать pip3 --upgrade install rupo.
Во-вторых, могу посоветовать заново распаковать файлики, они могли попортиться от предыдущего запуска.
В-третьих, проверить, нет ли в путях опечаток.

Ну до сих пор это было чисто моя недоработка.

**Comment by jhnmeelr** [comment]
`>>> engine.generate_poem('/Users/mbp/Google Drive/console/rupo/rupo/data/generator_models/lstm.h5', '/Users/mbp/Google Drive/console/rupo/rupo/data/generator_models/stress_vocabulary.pickle', '/Users/mbp/Google Drive/console/rupo/rupo/data/generator_models/grammeme_vectorizer.json', '/Users/mbp/Google Drive/console/rupo/rupo/data/generator_models/stress_vocabulary.pickle', beam_width=3, n_syllables=8)
Init vocabulary: 100%|███████████████████████| 1/1 [00:00<00:00, 3826.92it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbp/Google Drive/console/rupo/rupo/api.py", line 200, in generate_poem
    stress_vocab_dump_path, gram_dump_path)
  File "/Users/mbp/Google Drive/console/rupo/rupo/api.py", line 63, in get_lstm_generator
    lstm = LSTMModelContainer(model_path, word_form_vocab_dump_path, gram_dump_path)
  File "/Users/mbp/Google Drive/console/rupo/rupo/generate/language_model/lstm.py", line 232, in __init__
    self.lstm.prepare(list(), word_form_vocab_dump_path, gram_dump_path)
  File "/Users/mbp/Google Drive/console/rupo/rupo/generate/language_model/lstm.py", line 71, in prepare
    self.word_form_vocabulary.save()
  File "/Users/mbp/Google Drive/console/rupo/rupo/generate/prepare/word_form_vocabulary.py", line 42, in save
    with open(self.dump_filename, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yallen/Документы/Python/rupo/rupo/data/generator_models/word_form_vocabulary.pickle'`

"/home/yallen/Документы/" - какая-то статика. поправьте пути плиз

**Comment by IlyaGusev** [comment]
Аргументы неправильные же, stress_vocabulary 2 раза. Но статика - странный fallback на такой случай, разбираюсь
